class DataKeys {
  static const String
    LIST_OF_IDS = 'DATA_TODO__ALL_LIST'
  , COUNT = 'DATA_TODO__NOT_COMPLETED_COUNT'
  , GET_COUNT_COMPLETED = 'DATA_TODO__GET_COMPLETED_COUNT'
  , FILTER = 'DATA_TODO__FILTER'
  , COMPLETE_ALL = 'DATA_TODO__COMPLETE_ALL'
  , STATE = 'DATA_TODO__STATE'
  ;
}
