class ViewSignals {
  static const String INPUT = 'SIGNAL__INPUT_TODO',
      EDIT = 'SIGNAL__EDIT_TODO',
      DELETE = 'SIGNAL__DELETE_TODO',
      DISMISSED = 'SIGNAL__DISMISSED_TODO',
      TOGGLE = 'SIGNAL__TOGGLE_TODO',
      FILTER = 'SIGNAL__FILTER_TODO',
      CLEAR_INPUT = 'SIGNAL__CLEAR_TODO',
      CLEAR_COMPLETED = 'SIGNAL__CLEAR_COMPLETED',
      COMPLETE_ALL = 'SIGNAL__COMPLETE_ALL',
      COMPLETE_ALL_FORCED = 'SIGNAL__COMPLETE_ALL_FORCED';
}
